Traceback (most recent call last):
  File "maskcreate.py", line 74, in <module>
    hdu.writeto(sys.argv[3]) #sys.argv[3] = VCC????-I-Flag-Circ.fits
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 377, in writeto
    checksum=checksum)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 878, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 480, in _open_filename
    self._overwrite_existing(overwrite, None, True)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 401, in _overwrite_existing
    raise IOError("File {!r} already exists.".format(self.name))
OSError: File 'VCC2050-I-Flag-Circ.fits' already exists.
Traceback (most recent call last):
  File "pixel-flag-flip.py", line 26, in <module>
    f.writeto(sys.argv[2]) #sys.argv[2] = VCC???-I-Flag-Invert.fits
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 878, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 480, in _open_filename
    self._overwrite_existing(overwrite, None, True)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 401, in _overwrite_existing
    raise IOError("File {!r} already exists.".format(self.name))
OSError: File 'VCC2050-I-Flag-Invert.fits' already exists.
